name: 'publive'
services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27087:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - mongodb_data:/data/db

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data/redis

  # NestJS API Service
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: publive_api
    ports:
      - "5678:5678"
    depends_on:
      - mongodb
      - redis
    environment:
      - DATABASE_URI=mongodb://root:examplepassword@mongodb:27017/publive-dev?authSource=admin
      - REDIS_URL=redis://redis_container:6379
    volumes:
      - ../api:/usr/src/api
      - ../api/src/common/template:/usr/src/app/templates
      - ../api/public:/usr/src/app/public

  api2:
    build:
      context: ../api2
      dockerfile: Dockerfile
    container_name: publive_api_2
    ports:
      - "2072:2072"
    depends_on:
      - mongodb
      - redis
    environment:
      - DATABASE_URI=mongodb://root:examplepassword@mongodb:27017/publive-dev-2?authSource=admin
      - REDIS_URL=redis://redis_container:6379
    volumes:
      - ../api2:/usr/src/api2

volumes:
  mongodb_data:
  redis_data:
